//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ModificationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModificationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="AddSegment"/>
 *     &lt;enumeration value="RemoveSegment"/>
 *     &lt;enumeration value="ReplaceSegment"/>
 *     &lt;enumeration value="AddPassenger"/>
 *     &lt;enumeration value="RemovePassenger"/>
 *     &lt;enumeration value="OptionsOnly"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ModificationType {

    @XmlEnumValue("AddPassenger")
    ADD_PASSENGER("AddPassenger"),
    @XmlEnumValue("AddSegment")
    ADD_SEGMENT("AddSegment"),
    @XmlEnumValue("OptionsOnly")
    OPTIONS_ONLY("OptionsOnly"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("RemovePassenger")
    REMOVE_PASSENGER("RemovePassenger"),
    @XmlEnumValue("RemoveSegment")
    REMOVE_SEGMENT("RemoveSegment"),
    @XmlEnumValue("ReplaceSegment")
    REPLACE_SEGMENT("ReplaceSegment");
    private final String value;

    ModificationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModificationType fromValue(String v) {
        for (ModificationType c: ModificationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
