//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCreditCardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeCreditCardType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.travelport.com/schema/common_v28_0}typePaymentCard">
 *       &lt;attribute name="AcceptanceOverride" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="BankCountryCode" type="{http://www.travelport.com/schema/common_v28_0}typeCountry" />
 *       &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankStateCode" type="{http://www.travelport.com/schema/common_v28_0}typeState" />
 *       &lt;attribute name="CustomerReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExtendedPayment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ThirdPartyPayment" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeCreditCardType")
public class TypeCreditCardType
    extends TypePaymentCard
{

    @XmlAttribute(name = "AcceptanceOverride")
    protected Boolean acceptanceOverride;
    @XmlAttribute(name = "BankCountryCode")
    protected String bankCountryCode;
    @XmlAttribute(name = "BankName")
    protected String bankName;
    @XmlAttribute(name = "BankStateCode")
    protected String bankStateCode;
    @XmlAttribute(name = "CustomerReference")
    protected String customerReference;
    @XmlAttribute(name = "ExtendedPayment")
    protected String extendedPayment;
    @XmlAttribute(name = "ThirdPartyPayment")
    protected Boolean thirdPartyPayment;

    /**
     * Gets the value of the acceptanceOverride property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptanceOverride() {
        return acceptanceOverride;
    }

    /**
     * Sets the value of the acceptanceOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptanceOverride(Boolean value) {
        this.acceptanceOverride = value;
    }

    /**
     * Gets the value of the bankCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCountryCode() {
        return bankCountryCode;
    }

    /**
     * Sets the value of the bankCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCountryCode(String value) {
        this.bankCountryCode = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the bankStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankStateCode() {
        return bankStateCode;
    }

    /**
     * Sets the value of the bankStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankStateCode(String value) {
        this.bankStateCode = value;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the extendedPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedPayment() {
        return extendedPayment;
    }

    /**
     * Sets the value of the extendedPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedPayment(String value) {
        this.extendedPayment = value;
    }

    /**
     * Gets the value of the thirdPartyPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isThirdPartyPayment() {
        if (thirdPartyPayment == null) {
            return false;
        } else {
            return thirdPartyPayment;
        }
    }

    /**
     * Sets the value of the thirdPartyPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setThirdPartyPayment(Boolean value) {
        this.thirdPartyPayment = value;
    }

}
