//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * ProfileEntityID and ProfileLevel together identity a profile entity.
 * 
 * <p>Java class for typeProfileRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeProfileRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ProfileEntityID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ProfileLevel" use="required" type="{http://www.travelport.com/schema/common_v28_0}typeProfileLevel" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeProfileRef")
public class TypeProfileRef {

    @XmlAttribute(name = "ProfileEntityID", required = true)
    protected String profileEntityID;
    @XmlAttribute(name = "ProfileLevel", required = true)
    protected TypeProfileLevel profileLevel;

    /**
     * Gets the value of the profileEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileEntityID() {
        return profileEntityID;
    }

    /**
     * Sets the value of the profileEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileEntityID(String value) {
        this.profileEntityID = value;
    }

    /**
     * Gets the value of the profileLevel property.
     * 
     * @return
     *     possible object is
     *     {@link TypeProfileLevel }
     *     
     */
    public TypeProfileLevel getProfileLevel() {
        return profileLevel;
    }

    /**
     * Sets the value of the profileLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeProfileLevel }
     *     
     */
    public void setProfileLevel(TypeProfileLevel value) {
        this.profileLevel = value;
    }

}
