//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type which can be used for flexible date/time specification -extends the generic type typeTimeSpec to provide extra options for search.
 * 
 * <p>Java class for typeFlexibleTimeSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeFlexibleTimeSpec">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.travelport.com/schema/common_v28_0}typeTimeSpec">
 *       &lt;sequence>
 *         &lt;element name="SearchExtraDays" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DaysAfter" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="DaysBefore" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeFlexibleTimeSpec", propOrder = {
    "searchExtraDays"
})
public class TypeFlexibleTimeSpec
    extends TypeTimeSpec
{

    @XmlElement(name = "SearchExtraDays")
    protected TypeFlexibleTimeSpec.SearchExtraDays searchExtraDays;

    /**
     * Gets the value of the searchExtraDays property.
     * 
     * @return
     *     possible object is
     *     {@link SearchExtraDays }
     *     
     */
    public SearchExtraDays getSearchExtraDays() {
        return searchExtraDays;
    }

    /**
     * Sets the value of the searchExtraDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchExtraDays }
     *     
     */
    public void setSearchExtraDays(SearchExtraDays value) {
        this.searchExtraDays = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DaysAfter" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="DaysBefore" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SearchExtraDays {

        @XmlAttribute(name = "DaysAfter")
        protected Integer daysAfter;
        @XmlAttribute(name = "DaysBefore")
        protected Integer daysBefore;

        /**
         * Gets the value of the daysAfter property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDaysAfter() {
            return daysAfter;
        }

        /**
         * Sets the value of the daysAfter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDaysAfter(Integer value) {
            this.daysAfter = value;
        }

        /**
         * Gets the value of the daysBefore property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDaysBefore() {
            return daysBefore;
        }

        /**
         * Sets the value of the daysBefore property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDaysBefore(Integer value) {
            this.daysBefore = value;
        }

    }

}
