//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Passenger type code with optional age information
 * 
 * <p>Java class for typePassengerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typePassengerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.travelport.com/schema/common_v28_0}Name" minOccurs="0"/>
 *         &lt;element ref="{http://www.travelport.com/schema/common_v28_0}LoyaltyCard" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.travelport.com/schema/common_v28_0}DiscountCard" maxOccurs="9" minOccurs="0"/>
 *         &lt;element ref="{http://www.travelport.com/schema/common_v28_0}PersonalGeography" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AccompaniedPassenger" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Age" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BookingTravelerRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Code" use="required" type="{http://www.travelport.com/schema/common_v28_0}typePTC" />
 *       &lt;attribute name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Gender" type="{http://www.travelport.com/schema/common_v28_0}typeGender" />
 *       &lt;attribute name="PricePTCOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ResidencyType" type="{http://www.travelport.com/schema/common_v28_0}typeResidency" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typePassengerType", propOrder = {
    "name",
    "loyaltyCard",
    "discountCard",
    "personalGeography"
})
public class TypePassengerType {

    @XmlElement(name = "Name")
    protected Name name;
    @XmlElement(name = "LoyaltyCard", required = true)
    protected List<LoyaltyCard> loyaltyCard;
    @XmlElement(name = "DiscountCard", required = true)
    protected List<DiscountCard> discountCard;
    @XmlElement(name = "PersonalGeography")
    protected PersonalGeography personalGeography;
    @XmlAttribute(name = "AccompaniedPassenger")
    protected Boolean accompaniedPassenger;
    @XmlAttribute(name = "Age")
    protected BigInteger age;
    @XmlAttribute(name = "BookingTravelerRef")
    protected String bookingTravelerRef;
    @XmlAttribute(name = "Code", required = true)
    protected String code;
    @XmlAttribute(name = "DOB")
    protected XMLGregorianCalendar dob;
    @XmlAttribute(name = "Gender")
    protected String gender;
    @XmlAttribute(name = "PricePTCOnly")
    protected Boolean pricePTCOnly;
    @XmlAttribute(name = "ResidencyType")
    protected TypeResidency residencyType;

    /**
     * Optional passenger Name with associated LoyaltyCard may provide benefit when pricing itineraries using Low Cost Carriers. In general, most carriers do not consider passenger LoyalyCard information when initially pricing itineraries.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Optional passenger Name with associated LoyaltyCard may provide benefit when pricing itineraries using Low Cost Carriers. In general, most carriers do not consider passenger LoyalyCard information when initially pricing itineraries.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the loyaltyCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loyaltyCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoyaltyCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoyaltyCard }
     * 
     * 
     */
    public List<LoyaltyCard> getLoyaltyCard() {
        if (loyaltyCard == null) {
            loyaltyCard = new ArrayList<LoyaltyCard>();
        }
        return this.loyaltyCard;
    }

    /**
     * Gets the value of the discountCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiscountCard }
     * 
     * 
     */
    public List<DiscountCard> getDiscountCard() {
        if (discountCard == null) {
            discountCard = new ArrayList<DiscountCard>();
        }
        return this.discountCard;
    }

    /**
     * Passenger personal geography detail to be sent to Host for accessing location specific fares
     * 
     * @return
     *     possible object is
     *     {@link PersonalGeography }
     *     
     */
    public PersonalGeography getPersonalGeography() {
        return personalGeography;
    }

    /**
     * Passenger personal geography detail to be sent to Host for accessing location specific fares
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalGeography }
     *     
     */
    public void setPersonalGeography(PersonalGeography value) {
        this.personalGeography = value;
    }

    /**
     * Gets the value of the accompaniedPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAccompaniedPassenger() {
        if (accompaniedPassenger == null) {
            return false;
        } else {
            return accompaniedPassenger;
        }
    }

    /**
     * Sets the value of the accompaniedPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccompaniedPassenger(Boolean value) {
        this.accompaniedPassenger = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAge(BigInteger value) {
        this.age = value;
    }

    /**
     * Gets the value of the bookingTravelerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingTravelerRef() {
        return bookingTravelerRef;
    }

    /**
     * Sets the value of the bookingTravelerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingTravelerRef(String value) {
        this.bookingTravelerRef = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOB(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the pricePTCOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPricePTCOnly() {
        return pricePTCOnly;
    }

    /**
     * Sets the value of the pricePTCOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPricePTCOnly(Boolean value) {
        this.pricePTCOnly = value;
    }

    /**
     * Gets the value of the residencyType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeResidency }
     *     
     */
    public TypeResidency getResidencyType() {
        return residencyType;
    }

    /**
     * Sets the value of the residencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeResidency }
     *     
     */
    public void setResidencyType(TypeResidency value) {
        this.residencyType = value;
    }

}
