//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeFuel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeFuel">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Petrol"/>
 *     &lt;enumeration value="Diesel"/>
 *     &lt;enumeration value="Hybrid"/>
 *     &lt;enumeration value="Electric"/>
 *     &lt;enumeration value="LPGCNG"/>
 *     &lt;enumeration value="Hydrogen"/>
 *     &lt;enumeration value="MultiFuel"/>
 *     &lt;enumeration value="Ethanol"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeFuel {

    @XmlEnumValue("Diesel")
    DIESEL("Diesel"),
    @XmlEnumValue("Electric")
    ELECTRIC("Electric"),
    @XmlEnumValue("Ethanol")
    ETHANOL("Ethanol"),
    @XmlEnumValue("Hybrid")
    HYBRID("Hybrid"),
    @XmlEnumValue("Hydrogen")
    HYDROGEN("Hydrogen"),
    LPGCNG("LPGCNG"),
    @XmlEnumValue("MultiFuel")
    MULTI_FUEL("MultiFuel"),
    @XmlEnumValue("Petrol")
    PETROL("Petrol");
    private final String value;

    TypeFuel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeFuel fromValue(String v) {
        for (TypeFuel c: TypeFuel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
