//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeElement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeElement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Payment"/>
 *     &lt;enumeration value="CreditCardAuthorization"/>
 *     &lt;enumeration value="DeliveryInfo"/>
 *     &lt;enumeration value="FormOfPayment"/>
 *     &lt;enumeration value="ActionStatus"/>
 *     &lt;enumeration value="OSI"/>
 *     &lt;enumeration value="GeneralRemark"/>
 *     &lt;enumeration value="UnassociatedRemark"/>
 *     &lt;enumeration value="AccountingRemark"/>
 *     &lt;enumeration value="PostScript"/>
 *     &lt;enumeration value="AirReservationAirSegmentUpdate"/>
 *     &lt;enumeration value="AirSegment"/>
 *     &lt;enumeration value="PhoneNumber"/>
 *     &lt;enumeration value="Email"/>
 *     &lt;enumeration value="LoyaltyCard"/>
 *     &lt;enumeration value="SSR"/>
 *     &lt;enumeration value="SeatAssignment"/>
 *     &lt;enumeration value="SpecificSeatAssignment"/>
 *     &lt;enumeration value="AutoSeatAssignment"/>
 *     &lt;enumeration value="AirPricingInfo"/>
 *     &lt;enumeration value="VehicleSpecialRequest"/>
 *     &lt;enumeration value="SpecialEquipment"/>
 *     &lt;enumeration value="XMLRemark"/>
 *     &lt;enumeration value="Address"/>
 *     &lt;enumeration value="TicketingModifiers"/>
 *     &lt;enumeration value="Guarantee"/>
 *     &lt;enumeration value="DeliveryAddress"/>
 *     &lt;enumeration value="ServiceFeeInfo"/>
 *     &lt;enumeration value="LinkedUniversalRecord"/>
 *     &lt;enumeration value="NameRemark"/>
 *     &lt;enumeration value="PassiveSegment"/>
 *     &lt;enumeration value="PaymentInformation"/>
 *     &lt;enumeration value="CustomerID"/>
 *     &lt;enumeration value="DriversLicense"/>
 *     &lt;enumeration value="AssociatedRemark"/>
 *     &lt;enumeration value="CollectionAddress"/>
 *     &lt;enumeration value="HotelSpecialRequest"/>
 *     &lt;enumeration value="CorporateDiscountID"/>
 *     &lt;enumeration value="CommissionRemark"/>
 *     &lt;enumeration value="PocketItineraryRemark"/>
 *     &lt;enumeration value="CustomizedNameData"/>
 *     &lt;enumeration value="InvoiceRemark"/>
 *     &lt;enumeration value="ThirdPartyInformation"/>
 *     &lt;enumeration value="TravelCompliance"/>
 *     &lt;enumeration value="ReviewBooking"/>
 *     &lt;enumeration value="ConsolidatorRemark"/>
 *     &lt;enumeration value="BookingTraveler"/>
 *     &lt;enumeration value="AppliedProfile"/>
 *     &lt;enumeration value="TripName"/>
 *     &lt;enumeration value="TravelPurpose"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeElement {

    @XmlEnumValue("AccountingRemark")
    ACCOUNTING_REMARK("AccountingRemark"),
    @XmlEnumValue("ActionStatus")
    ACTION_STATUS("ActionStatus"),
    @XmlEnumValue("Address")
    ADDRESS("Address"),
    @XmlEnumValue("AirPricingInfo")
    AIR_PRICING_INFO("AirPricingInfo"),
    @XmlEnumValue("AirReservationAirSegmentUpdate")
    AIR_RESERVATION_AIR_SEGMENT_UPDATE("AirReservationAirSegmentUpdate"),
    @XmlEnumValue("AirSegment")
    AIR_SEGMENT("AirSegment"),
    @XmlEnumValue("AppliedProfile")
    APPLIED_PROFILE("AppliedProfile"),
    @XmlEnumValue("AssociatedRemark")
    ASSOCIATED_REMARK("AssociatedRemark"),
    @XmlEnumValue("AutoSeatAssignment")
    AUTO_SEAT_ASSIGNMENT("AutoSeatAssignment"),
    @XmlEnumValue("BookingTraveler")
    BOOKING_TRAVELER("BookingTraveler"),
    @XmlEnumValue("CollectionAddress")
    COLLECTION_ADDRESS("CollectionAddress"),
    @XmlEnumValue("CommissionRemark")
    COMMISSION_REMARK("CommissionRemark"),
    @XmlEnumValue("ConsolidatorRemark")
    CONSOLIDATOR_REMARK("ConsolidatorRemark"),
    @XmlEnumValue("CorporateDiscountID")
    CORPORATE_DISCOUNT_ID("CorporateDiscountID"),
    @XmlEnumValue("CreditCardAuthorization")
    CREDIT_CARD_AUTHORIZATION("CreditCardAuthorization"),
    @XmlEnumValue("CustomerID")
    CUSTOMER_ID("CustomerID"),
    @XmlEnumValue("CustomizedNameData")
    CUSTOMIZED_NAME_DATA("CustomizedNameData"),
    @XmlEnumValue("DeliveryAddress")
    DELIVERY_ADDRESS("DeliveryAddress"),
    @XmlEnumValue("DeliveryInfo")
    DELIVERY_INFO("DeliveryInfo"),
    @XmlEnumValue("DriversLicense")
    DRIVERS_LICENSE("DriversLicense"),
    @XmlEnumValue("Email")
    EMAIL("Email"),
    @XmlEnumValue("FormOfPayment")
    FORM_OF_PAYMENT("FormOfPayment"),
    @XmlEnumValue("GeneralRemark")
    GENERAL_REMARK("GeneralRemark"),
    @XmlEnumValue("Guarantee")
    GUARANTEE("Guarantee"),
    @XmlEnumValue("HotelSpecialRequest")
    HOTEL_SPECIAL_REQUEST("HotelSpecialRequest"),
    @XmlEnumValue("InvoiceRemark")
    INVOICE_REMARK("InvoiceRemark"),
    @XmlEnumValue("LinkedUniversalRecord")
    LINKED_UNIVERSAL_RECORD("LinkedUniversalRecord"),
    @XmlEnumValue("LoyaltyCard")
    LOYALTY_CARD("LoyaltyCard"),
    @XmlEnumValue("NameRemark")
    NAME_REMARK("NameRemark"),
    OSI("OSI"),
    @XmlEnumValue("PassiveSegment")
    PASSIVE_SEGMENT("PassiveSegment"),
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),
    @XmlEnumValue("PaymentInformation")
    PAYMENT_INFORMATION("PaymentInformation"),
    @XmlEnumValue("PhoneNumber")
    PHONE_NUMBER("PhoneNumber"),
    @XmlEnumValue("PocketItineraryRemark")
    POCKET_ITINERARY_REMARK("PocketItineraryRemark"),
    @XmlEnumValue("PostScript")
    POST_SCRIPT("PostScript"),
    @XmlEnumValue("ReviewBooking")
    REVIEW_BOOKING("ReviewBooking"),
    @XmlEnumValue("SeatAssignment")
    SEAT_ASSIGNMENT("SeatAssignment"),
    @XmlEnumValue("ServiceFeeInfo")
    SERVICE_FEE_INFO("ServiceFeeInfo"),
    @XmlEnumValue("SpecialEquipment")
    SPECIAL_EQUIPMENT("SpecialEquipment"),
    @XmlEnumValue("SpecificSeatAssignment")
    SPECIFIC_SEAT_ASSIGNMENT("SpecificSeatAssignment"),
    SSR("SSR"),
    @XmlEnumValue("ThirdPartyInformation")
    THIRD_PARTY_INFORMATION("ThirdPartyInformation"),
    @XmlEnumValue("TicketingModifiers")
    TICKETING_MODIFIERS("TicketingModifiers"),
    @XmlEnumValue("TravelCompliance")
    TRAVEL_COMPLIANCE("TravelCompliance"),
    @XmlEnumValue("TravelPurpose")
    TRAVEL_PURPOSE("TravelPurpose"),
    @XmlEnumValue("TripName")
    TRIP_NAME("TripName"),
    @XmlEnumValue("UnassociatedRemark")
    UNASSOCIATED_REMARK("UnassociatedRemark"),
    @XmlEnumValue("VehicleSpecialRequest")
    VEHICLE_SPECIAL_REQUEST("VehicleSpecialRequest"),
    @XmlEnumValue("XMLRemark")
    XML_REMARK("XMLRemark");
    private final String value;

    TypeElement(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeElement fromValue(String v) {
        for (TypeElement c: TypeElement.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
