//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeVehicleCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeVehicleCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Car"/>
 *     &lt;enumeration value="Van"/>
 *     &lt;enumeration value="SUV"/>
 *     &lt;enumeration value="Convertible"/>
 *     &lt;enumeration value="Truck"/>
 *     &lt;enumeration value="StationWagon"/>
 *     &lt;enumeration value="Pickup"/>
 *     &lt;enumeration value="AllTerrain"/>
 *     &lt;enumeration value="Recreational"/>
 *     &lt;enumeration value="Sport"/>
 *     &lt;enumeration value="Special"/>
 *     &lt;enumeration value="ExtendedCabPickup"/>
 *     &lt;enumeration value="RegularCabPickup"/>
 *     &lt;enumeration value="SpecialOffer"/>
 *     &lt;enumeration value="Coupe"/>
 *     &lt;enumeration value="Monospace"/>
 *     &lt;enumeration value="Roadster"/>
 *     &lt;enumeration value="Crossover"/>
 *     &lt;enumeration value="Motorcycle"/>
 *     &lt;enumeration value="Limo"/>
 *     &lt;enumeration value="Motorhome"/>
 *     &lt;enumeration value="TwoWheelVehicle"/>
 *     &lt;enumeration value="CommercialVanOrTruck"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeVehicleCategory {

    @XmlEnumValue("AllTerrain")
    ALL_TERRAIN("AllTerrain"),
    @XmlEnumValue("Car")
    CAR("Car"),
    @XmlEnumValue("CommercialVanOrTruck")
    COMMERCIAL_VAN_OR_TRUCK("CommercialVanOrTruck"),
    @XmlEnumValue("Convertible")
    CONVERTIBLE("Convertible"),
    @XmlEnumValue("Coupe")
    COUPE("Coupe"),
    @XmlEnumValue("Crossover")
    CROSSOVER("Crossover"),
    @XmlEnumValue("ExtendedCabPickup")
    EXTENDED_CAB_PICKUP("ExtendedCabPickup"),
    @XmlEnumValue("Limo")
    LIMO("Limo"),
    @XmlEnumValue("Monospace")
    MONOSPACE("Monospace"),
    @XmlEnumValue("Motorcycle")
    MOTORCYCLE("Motorcycle"),
    @XmlEnumValue("Motorhome")
    MOTORHOME("Motorhome"),
    @XmlEnumValue("Pickup")
    PICKUP("Pickup"),
    @XmlEnumValue("Recreational")
    RECREATIONAL("Recreational"),
    @XmlEnumValue("RegularCabPickup")
    REGULAR_CAB_PICKUP("RegularCabPickup"),
    @XmlEnumValue("Roadster")
    ROADSTER("Roadster"),
    @XmlEnumValue("Special")
    SPECIAL("Special"),
    @XmlEnumValue("SpecialOffer")
    SPECIAL_OFFER("SpecialOffer"),
    @XmlEnumValue("Sport")
    SPORT("Sport"),
    @XmlEnumValue("StationWagon")
    STATION_WAGON("StationWagon"),
    SUV("SUV"),
    @XmlEnumValue("Truck")
    TRUCK("Truck"),
    @XmlEnumValue("TwoWheelVehicle")
    TWO_WHEEL_VEHICLE("TwoWheelVehicle"),
    @XmlEnumValue("Van")
    VAN("Van");
    private final String value;

    TypeVehicleCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeVehicleCategory fromValue(String v) {
        for (TypeVehicleCategory c: TypeVehicleCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
