//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeCommissionModifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCommissionModifier">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FarePercent"/>
 *     &lt;enumeration value="FareAmount"/>
 *     &lt;enumeration value="CommissionAmount"/>
 *     &lt;enumeration value="LessStandardCommission"/>
 *     &lt;enumeration value="StandardPlusSupplementaryPercent"/>
 *     &lt;enumeration value="SupplementaryPercent"/>
 *     &lt;enumeration value="SupplementaryAmount"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeCommissionModifier {

    @XmlEnumValue("CommissionAmount")
    COMMISSION_AMOUNT("CommissionAmount"),
    @XmlEnumValue("FareAmount")
    FARE_AMOUNT("FareAmount"),
    @XmlEnumValue("FarePercent")
    FARE_PERCENT("FarePercent"),
    @XmlEnumValue("LessStandardCommission")
    LESS_STANDARD_COMMISSION("LessStandardCommission"),
    @XmlEnumValue("StandardPlusSupplementaryPercent")
    STANDARD_PLUS_SUPPLEMENTARY_PERCENT("StandardPlusSupplementaryPercent"),
    @XmlEnumValue("SupplementaryAmount")
    SUPPLEMENTARY_AMOUNT("SupplementaryAmount"),
    @XmlEnumValue("SupplementaryPercent")
    SUPPLEMENTARY_PERCENT("SupplementaryPercent");
    private final String value;

    TypeCommissionModifier(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCommissionModifier fromValue(String v) {
        for (TypeCommissionModifier c: TypeCommissionModifier.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
