//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 11:27:55 AM MDT 
//


package com.wordpress.jonyonandroidcraftsmanship.travelportsoapconnector.com.travelport.uapi.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeFulfillmentIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeFulfillmentIDType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bahn Card"/>
 *     &lt;enumeration value="Credit Card"/>
 *     &lt;enumeration value="Euro Cheque Card"/>
 *     &lt;enumeration value="Collection Reference"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeFulfillmentIDType {

    @XmlEnumValue("Bahn Card")
    BAHN_CARD("Bahn Card"),
    @XmlEnumValue("Collection Reference")
    COLLECTION_REFERENCE("Collection Reference"),
    @XmlEnumValue("Credit Card")
    CREDIT_CARD("Credit Card"),
    @XmlEnumValue("Euro Cheque Card")
    EURO_CHEQUE_CARD("Euro Cheque Card");
    private final String value;

    TypeFulfillmentIDType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeFulfillmentIDType fromValue(String v) {
        for (TypeFulfillmentIDType c: TypeFulfillmentIDType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
